spring:
  config:
    import: classpath:/api/application-googleAPI.properties, classpath:/api/application-naverAPI.properties
  application:
    name: oauth2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
              - profile
              - email
          naver:
            client-id: ${naver-client-id}
            client-secret: ${naver-client-secret}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # 사용자가 클라이언트 서버에서 자원 요청시, 클아이언트 서버에서 인증 후 redirect 될 url -> 이후 toeken 요청(요청)
            #            scope:
            #              - name
            #              - email
            #              - profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 인증 유저에게 클라이언트 서버에게 리소스를 허용할 것인지 묻는 url
            token-uri: https://nid.naver.com/oauth2.0/token # 인증, 허용이 끝나면 클아이언트 서버에 코드가 발급되고, 클라이언트 서버는 이 코드를 통해 resource 서버에 access token url에 access token 을 요청
            user-info-uri: https://openapi.naver.com/v1/nid/me # access token을 통해 유저정보를 요청하는 url
            user-info-authentication-method: header # access token이 담길 위치
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정

#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-info-authentication-method: header
#            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정
